# importar csv

In [2]:
from google.colab import files
uploaded = files.upload()
uploaded

Saving Dados_tel.csv to Dados_tel.csv

{'Dados_tel.csv': b'timestamp,temperatura_interna_c,temperatura_externa_c,integridade_estrutural,nivel_energia_pct,pressao_tanque_bar,modulo_vida,modulo_propulsao,modulo_comunicacao,modulo_termico\r\n2026-03-24T00:00:00Z,22,-55,1,92,5.2,OK,OK,OK,OK\r\n2026-03-24T00:10:00Z,23,-57,1,90,5.1,OK,OK,OK,OK\r\n2026-03-24T00:20:00Z,24,-60,1,87,5.0,OK,OK,OK,OK\r\n2026-03-24T00:30:00Z,26,-62,1,83,4.9,OK,OK,OK,OK\r\n2026-03-24T00:40:00Z,28,-65,1,78,4.8,OK,OK,OK,WARN\r\n2026-03-24T00:50:00Z,30,-67,1,74,4.7,OK,OK,OK,WARN\r\n2026-03-24T01:00:00Z,32,-70,1,70,4.5,OK,OK,OK,FAIL\r\n2026-03-24T01:10:00Z,35,-72,1,66,4.3,OK,OK,WARN,FAIL\r\n2026-03-24T01:20:00Z,38,-75,1,61,4.1,OK,WARN,WARN,FAIL\r\n2026-03-24T01:30:00Z,40,-78,0,58,3.8,WARN,WARN,FAIL,FAIL\r\n2026-03-24T01:40:00Z,42,-80,0,52,3.5,WARN,FAIL,FAIL,FAIL\r\n2026-03-24T01:50:00Z,45,-82,0,47,3.2,FAIL,FAIL,FAIL,FAIL\r\n2026-03-24T02:00:00Z,48,-85,0,42,2.9,FAIL,FAIL,FAIL,FAIL'}

In [3]:
df = pd.read_csv(list(uploaded.keys())[0])
display(df)

,timestamp,temperatura_interna_c,temperatura_externa_c,integridade_estrutural,nivel_energia_pct,pressao_tanque_bar,modulo_vida,modulo_propulsao,modulo_comunicacao,modulo_termico
0,2026-03-24T00:00:00Z,22,-55,1,92,5.2,OK,OK,OK,OK
1,2026-03-24T00:10:00Z,23,-57,1,90,5.1,OK,OK,OK,OK
2,2026-03-24T00:20:00Z,24,-60,1,87,5.0,OK,OK,OK,OK
3,2026-03-24T00:30:00Z,26,-62,1,83,4.9,OK,OK,OK,OK
4,2026-03-24T00:40:00Z,28,-65,1,78,4.8,OK,OK,OK,WARN
5,2026-03-24T00:50:00Z,30,-67,1,74,4.7,OK,OK,OK,WARN
6,2026-03-24T01:00:00Z,32,-70,1,70,4.5,OK,OK,OK,FAIL
7,2026-03-24T01:10:00Z,35,-72,1,66,4.3,OK,OK,WARN,FAIL
8,2026-03-24T01:20:00Z,38,-75,1,61,4.1,OK,WARN,WARN,FAIL
9,2026-03-24T01:30:00Z,40,-78,0,58,3.8,WARN,WARN,FAIL,FAIL
10,2026-03-24T01:40:00Z,42,-80,0,52,3.5,WARN,FAIL,FAIL,FAIL
11,2026-03-24T01:50:00Z,45,-82,0,47,3.2,FAIL,FAIL,FAIL,FAIL
12,2026-03-24T02:00:00Z,48,-85,0,42,2.9,FAIL,FAIL,FAIL,FAIL

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp               13 non-null     object
 1   temperatura_interna_c   13 non-null     int64
 2   temperatura_externa_c   13 non-null     int64
 3   integridade_estrutural  13 non-null     int64
 4   nivel_energia_pct       13 non-null     int64
 5   pressao_tanque_bar      13 non-null     float64
 6   modulo_vida             13 non-null     object
 7   modulo_propulsao        13 non-null     object
 8   modulo_comunicacao      13 non-null     object
 9   modulo_termico          13 non-null     object
dtypes: float64(1), int64(4), object(5)
memory usage: 1.1+ KB

In [5]:
df.describe()

,temperatura_interna_c,temperatura_externa_c,integridade_estrutural,nivel_energia_pct,pressao_tanque_bar
count,13.000000,13.000000,13.000000,13.000000,13.000000
mean,33.307692,-69.846154,0.692308,69.230769,4.307692
std,8.721474,9.805153,0.480384,16.563785,0.755493
min,22.000000,-85.000000,0.000000,42.000000,2.900000
25%,26.000000,-78.000000,0.000000,58.000000,3.800000
50%,32.000000,-70.000000,1.000000,70.000000,4.500000
75%,40.000000,-62.000000,1.000000,83.000000,4.900000
max,48.000000,-55.000000,1.000000,92.000000,5.200000

# SCRIPT

In [12]:
import pandas as pd

file_path = 'Dados_tel.csv'

data_frame = pd.read_csv(file_path)

df = pd.read_csv(file_path)

print(df)

def avaliar_lancamento(df_data):
    df_data['pressao_tanque_bar'] = pd.to_numeric(df_data['pressao_tanque_bar'], errors='coerce')

    estado = df_data.iloc[-1]

    motivos = []

    if estado["integridade_estrutural"] == 0:
        motivos.append("Falha estrutural")

    if estado["temperatura_interna_c"] > 35:
        motivos.append("Temperatura interna crítica")

    if estado["nivel_energia_pct"] < 60:
        motivos.append("Energia insuficiente")

    if estado["pressao_tanque_bar"] < 4.0:
        motivos.append("Pressão dos tanques baixa")

    modulos = [
        "modulo_vida",
        "modulo_propulsao",
        "modulo_comunicacao",
        "modulo_termico"
    ]

    for m in modulos:
        if estado[m] == "FAIL":
            motivos.append(f"Falha no {m}")

    # Resultado final
    if len(motivos) == 0:
        return "✅ LANÇAMENTO PERMITIDO", []
    else:
        return "❌ LANÇAMENTO NÃO PERMITIDO", motivos


# Exemplo de uso
status, problemas = avaliar_lancamento(df)

print(status)

if problemas:
    print("\nMotivos:")
    for p in problemas:
        print("- ", p)

               timestamp  temperatura_interna_c  temperatura_externa_c  \
0   2026-03-24T00:00:00Z                     22                    -55
1   2026-03-24T00:10:00Z                     23                    -57
2   2026-03-24T00:20:00Z                     24                    -60
3   2026-03-24T00:30:00Z                     26                    -62
4   2026-03-24T00:40:00Z                     28                    -65
5   2026-03-24T00:50:00Z                     30                    -67
6   2026-03-24T01:00:00Z                     32                    -70
7   2026-03-24T01:10:00Z                     35                    -72
8   2026-03-24T01:20:00Z                     38                    -75
9   2026-03-24T01:30:00Z                     40                    -78
10  2026-03-24T01:40:00Z                     42                    -80
11  2026-03-24T01:50:00Z                     45                    -82
12  2026-03-24T02:00:00Z                     48                    -85

    integridade_estrutural  nivel_energia_pct  pressao_tanque_bar modulo_vida  \
0                        1                 92                 5.2          OK
1                        1                 90                 5.1          OK
2                        1                 87                 5.0          OK
3                        1                 83                 4.9          OK
4                        1                 78                 4.8          OK
5                        1                 74                 4.7          OK
6                        1                 70                 4.5          OK
7                        1                 66                 4.3          OK
8                        1                 61                 4.1          OK
9                        0                 58                 3.8        WARN
10                       0                 52                 3.5        WARN
11                       0                 47                 3.2        FAIL
12                       0                 42                 2.9        FAIL

   modulo_propulsao modulo_comunicacao modulo_termico
0                OK                 OK             OK
1                OK                 OK             OK
2                OK                 OK             OK
3                OK                 OK             OK
4                OK                 OK           WARN
5                OK                 OK           WARN
6                OK                 OK           FAIL
7                OK               WARN           FAIL
8              WARN               WARN           FAIL
9              WARN               FAIL           FAIL
10             FAIL               FAIL           FAIL
11             FAIL               FAIL           FAIL
12             FAIL               FAIL           FAIL
❌ LANÇAMENTO NÃO PERMITIDO

Motivos:
-  Falha estrutural
-  Temperatura interna crítica
-  Energia insuficiente
-  Pressão dos tanques baixa
-  Falha no modulo_vida
-  Falha no modulo_propulsao
-  Falha no modulo_comunicacao
-  Falha no modulo_termico